export const START_FETCHING_LISTS_CATEGORIES =
  'redux/lists/START_FETCHING_LISTS_CATEGORIES';
export const SUCCESS_FETCHING_LISTS_CATEGORIES =
  'redux/lists/SUCCESS_FETCHING_LISTS_CATEGORIES';
export const ERROR_FETCHING_LISTS_CATEGORIES =
  'redux/lists/ERROR_FETCHING_LISTS_CATEGORIES';

export const START_FETCHING_LISTS_SPEAKERS =
  'redux/lists/START_FETCHING_LISTS_SPEAKERS';
export const SUCCESS_FETCHING_LISTS_SPEAKERS =
  'redux/lists/SUCCESS_FETCHING_LISTS_SPEAKERS';
export const ERROR_FETCHING_LISTS_SPEAKERS =
  'redux/lists/ERROR_FETCHING_LISTS_SPEAKERS';

export const START_FETCHING_LISTS_EVENTS =
  'redux/lists/START_FETCHING_LISTS_EVENTS';
export const SUCCESS_FETCHING_LISTS_EVENTS =
  'redux/lists/SUCCESS_FETCHING_LISTS_EVENTS';
export const ERROR_FETCHING_LISTS_EVENTS =
  'redux/lists/ERROR_FETCHING_LISTS_EVENTS';
